#genomes_location: /home/ctbrown/gtdbtk/release89/fastani
genomes_location: database-test/
sigs_output_location: database-test-foo/
gtdb_taxonomy_tsv: /home/ctbrown/gtdbtk/release89/taxonomy/gtdb_taxonomy.tsv
